// ─── Carbohydrate-Only Nodes ─────────────────────────────────────────────────
export const NODES = [
  {
    id: 'carbohydrates',
    label: 'Carbohydrates',
    sublabel: 'Hydrated Carbons — Overview',
    color: '#3ddc84',
    emissive: '#1a6640',
    position: [0, 0, 0],
    size: 0.38,
    coords: { x: 104, y: 22, z: 0 },
    isPrimary: true,
    logs: [
      {
        id: '01',
        title: 'General Context',
        type: 'text',
        content: `Carbohydrates are organic molecules composed of carbon (C), hydrogen (H), and oxygen (O) with a characteristic 2:1 hydrogen-to-oxygen ratio — effectively "hydrated carbons" (Cₙ(H₂O)ₙ). They are the most abundant biomolecules on Earth, serving as the primary fuel source for cellular metabolism and providing critical structural support across all domains of life.`,
        credit: 'David Bassem',
      },
      {
        id: '02',
        title: 'The Atoms',
        type: 'atoms',
        content: null,
        credit: 'David Bassem',
        atoms: [
          { symbol: 'C', name: 'Carbon', color: '#a3e635', desc: 'The backbone scaffold. Carbon\'s tetravalency (4 bonds) enables the branched and linear chain structures that define carbohydrate diversity. Typically makes up 40–44% of dry carbohydrate mass.' },
          { symbol: 'H', name: 'Hydrogen', color: '#60a5fa', desc: 'The energy-dense bonding agent. High-energy C–H bonds store chemical potential energy released during glycolysis and the Krebs cycle. Makes up ~6% of carbohydrate mass.' },
          { symbol: 'O', name: 'Oxygen', color: '#f87171', desc: 'The high-octane component. Present as hydroxyl (–OH) and carbonyl (C=O) groups. Drives fast aerobic metabolism by acting as the terminal electron acceptor in cellular respiration.' },
        ],
      },
      {
        id: '03',
        title: 'Why Are They Essential?',
        type: 'text',
        content: `Without carbohydrates, cells lack their primary energy currency. The brain alone consumes ~120g of glucose daily. They also form the physical backbone of DNA/RNA (ribose, deoxyribose), plant cell walls (cellulose), and insect/fungal armor (chitin). A world without carbohydrates means no wood, no cotton, no paper, no blood type compatibility — and no life.`,
        credit: 'David Bassem',
      },
    ],
  },

  {
    id: 'monosaccharides',
    label: 'Monosaccharides',
    sublabel: 'Simple Sugars — Monomers',
    color: '#facc15',
    emissive: '#713f12',
    position: [-3.0, 0.2, 1.2],
    size: 0.27,
    coords: { x: 48, y: 81, z: 4 },
    isPrimary: false,
    logs: [
      {
        id: '01',
        title: 'General Context',
        type: 'text',
        content: `Monosaccharides are the simplest carbohydrate units — single sugar molecules that cannot be hydrolyzed into smaller carbohydrates. They are the fundamental building blocks (monomers) from which all larger carbohydrates (disaccharides, polysaccharides) are assembled via glycosidic bonds. Their general formula is (CH₂O)ₙ where n ≥ 3.`,
        credit: 'Steven Ayman',
      },
      {
        id: '02',
        title: 'Key Examples',
        type: 'atoms',
        content: null,
        credit: 'Steven Ayman',
        atoms: [
          { symbol: 'Glc', name: 'Glucose (C₆H₁₂O₆)', color: '#facc15', desc: 'Blood sugar. The primary energy source for cells. Produced by photosynthesis. Exists as α-glucose (starch building block) and β-glucose (cellulose building block).' },
          { symbol: 'Fru', name: 'Fructose (C₆H₁₂O₆)', color: '#fb923c', desc: 'Fruit sugar. The sweetest naturally occurring sugar. Found in honey, fruits, and high-fructose corn syrup. Isomer of glucose.' },
          { symbol: 'Gal', name: 'Galactose (C₆H₁₂O₆)', color: '#a78bfa', desc: 'Milk sugar component. Combined with glucose to form lactose. Important for brain development in infants — found in cerebrosides (brain lipids).' },
          { symbol: 'Rib', name: 'Ribose (C₅H₁₀O₅)', color: '#f472b6', desc: 'Pentose sugar forming the backbone of RNA. One oxygen atom less gives deoxyribose (C₅H₁₀O₄) — the backbone of DNA.' },
        ],
      },
      {
        id: '03',
        title: 'Structural Note',
        type: 'text',
        content: `In solution, monosaccharides with 5+ carbons spontaneously cyclize into ring structures. Glucose forms a 6-membered pyranose ring, while fructose forms a 5-membered furanose ring. This ring chemistry determines whether a sugar links into starch (α-1,4 bonds) or cellulose (β-1,4 bonds) — a single orientation difference with enormous biological consequences.`,
        credit: 'Steven Ayman',
      },
    ],
  },

  {
    id: 'disaccharides',
    label: 'Disaccharides',
    sublabel: 'Two-Sugar Molecules',
    color: '#fb923c',
    emissive: '#7c2d12',
    position: [3.0, 0.3, 1.5],
    size: 0.24,
    coords: { x: 208, y: 57, z: 8 },
    isPrimary: false,
    logs: [
      {
        id: '01',
        title: 'General Context',
        type: 'text',
        content: `Disaccharides are formed when two monosaccharides are joined by a glycosidic bond — a covalent bond formed via a condensation (dehydration) reaction that releases one water molecule (H₂O). They can be broken apart again by hydrolysis (adding water). Disaccharides serve as transport forms and dietary sugars.`,
        credit: 'Seif Mohmmed',
      },
      {
        id: '02',
        title: 'Key Examples',
        type: 'atoms',
        content: null,
        credit: 'Seif Mohmmed',
        atoms: [
          { symbol: 'Suc', name: 'Sucrose — Table Sugar', color: '#fb923c', desc: 'Glucose + Fructose (α-1,β-2 bond). The primary transport sugar in plants, moved through phloem. Table sugar derived from sugar cane and sugar beet.' },
          { symbol: 'Lac', name: 'Lactose — Milk Sugar', color: '#fbbf24', desc: 'Glucose + Galactose (β-1,4 bond). Found in mammalian milk. Lactose intolerance occurs when the enzyme lactase is absent, preventing breakdown.' },
          { symbol: 'Mlt', name: 'Maltose — Malt Sugar', color: '#a3e635', desc: 'Glucose + Glucose (α-1,4 bond). Produced during starch digestion by amylase. Present in germinating seeds and malted barley (beer brewing).' },
        ],
      },
      {
        id: '03',
        title: 'Condensation & Hydrolysis',
        type: 'text',
        content: `The glycosidic bond is formed by condensation: A–OH + HO–B → A–O–B + H₂O. Enzymes called glycoside hydrolases (e.g., sucrase, lactase, maltase) catalyze the reverse reaction — hydrolysis — breaking the bond during digestion. The specific enzyme needed depends on the exact type and orientation of the glycosidic bond.`,
        credit: 'Seif Mohmmed',
      },
    ],
  },

  {
    id: 'polysaccharides',
    label: 'Polysaccharides',
    sublabel: 'Complex Carbohydrate Chains',
    color: '#22d3ee',
    emissive: '#164e63',
    position: [1.8, 0.1, -2.8],
    size: 0.30,
    coords: { x: 160, y: 190, z: 14 },
    isPrimary: false,
    logs: [
      {
        id: '01',
        title: 'General Context',
        type: 'text',
        content: `Polysaccharides are long-chain polymers of monosaccharides (typically glucose) linked by glycosidic bonds. They are the most abundant form of carbohydrates in nature. Their function depends critically on bond type and branching: α-glycosidic bonds create helical, digestible structures (starch/glycogen); β-glycosidic bonds create rigid, flat sheets (cellulose/chitin) that most organisms cannot digest.`,
        credit: 'Flavio Hesham',
      },
      {
        id: '02',
        title: 'Storage Polysaccharides',
        type: 'atoms',
        content: null,
        credit: 'Flavio Hesham',
        atoms: [
          { symbol: 'Stch', name: 'Starch', color: '#22d3ee', desc: 'Plant energy store. Two components: Amylose (unbranched, α-1,4 bonds, ~20%) and Amylopectin (branched, α-1,4 + α-1,6 bonds every 24–30 glucose units, ~80%). Found in potatoes, rice, wheat.' },
          { symbol: 'Glyc', name: 'Glycogen', color: '#a78bfa', desc: 'Animal/fungal energy store. Highly branched (α-1,6 branch every 8–12 glucose units) for rapid glucose mobilization. Stored in liver (~100g) and muscle (~400g) in humans.' },
        ],
      },
      {
        id: '03',
        title: 'Structural Polysaccharides',
        type: 'atoms',
        content: null,
        credit: 'Flavio Hesham',
        atoms: [
          { symbol: 'Cell', name: 'Cellulose', color: '#4ade80', desc: 'Most abundant organic molecule on Earth. β-1,4 glucose linkages create straight chains that form hydrogen-bonded microfibrils. Provides mechanical strength to plant cell walls. Humans cannot digest it (dietary fiber).' },
          { symbol: 'Chit', name: 'Chitin', color: '#f472b6', desc: 'Second most abundant polysaccharide. β-1,4-linked N-acetylglucosamine. Forms the exoskeleton of insects/crustaceans and fungal cell walls. Stronger than cellulose due to acetyl amino groups.' },
          { symbol: 'Pecp', name: 'Pectin', color: '#fb923c', desc: 'Structural polysaccharide in plant cell walls and middle lamella (between cells). Forms gels in the presence of Ca²⁺ ions. Used commercially as a gelling agent in jams and jellies.' },
        ],
      },
      {
        id: '04',
        title: 'Functional Reference Table',
        type: 'classification',
        content: null,
        credit: 'Kirellos George',
        groups: [],
        table: [
          { function: 'Short-term Energy', molecule: 'Glucose → ATP', location: 'Cytoplasm / Mitochondria' },
          { function: 'Storage (Plants)', molecule: 'Starch (Amylose + Amylopectin)', location: 'Chloroplast / Amyloplast' },
          { function: 'Storage (Animals)', molecule: 'Glycogen', location: 'Liver & Muscle Cells' },
          { function: 'Structure (Plants)', molecule: 'Cellulose', location: 'Primary Cell Wall' },
          { function: 'Structure (Fungi/Arthropods)', molecule: 'Chitin', location: 'Cell Wall / Exoskeleton' },
          { function: 'Cell Signaling', molecule: 'Glycoproteins / Glycolipids', location: 'Plasma Membrane (ABO blood types)' },
          { function: 'Genetic Backbone', molecule: 'Ribose / Deoxyribose', location: 'RNA / DNA in every cell' },
        ],
      },
    ],
  },

  {
    id: 'dnasugars',
    label: 'DNA & RNA Sugars',
    sublabel: 'Genetic Backbone — Ribose',
    color: '#f472b6',
    emissive: '#831843',
    position: [-2.2, 0.4, -2.2],
    size: 0.22,
    coords: { x: 66, y: 148, z: 18 },
    isPrimary: false,
    logs: [
      {
        id: '01',
        title: 'Backbone Logic',
        type: 'text',
        content: `Carbohydrates are not just fuel — they form the literal backbone of all genetic information. Ribose (C₅H₁₀O₅) and Deoxyribose (C₅H₁₀O₄) are pentose sugars that serve as the structural scaffold of RNA and DNA respectively. The single oxygen atom difference at the 2' carbon position defines the stability gap between transcription (RNA) and archival storage (DNA).`,
        credit: 'Kirellos George',
        highlight: true,
      },
      {
        id: '02',
        title: 'Ribose vs Deoxyribose',
        type: 'atoms',
        content: null,
        credit: 'Kirellos George',
        atoms: [
          { symbol: 'Rib', name: 'Ribose — C₅H₁₀O₅', color: '#f472b6', desc: 'Found in RNA and ATP. Has a hydroxyl (–OH) group at the 2\' carbon. More reactive — allows RNA to fold into 3D structures and catalyze reactions (ribozymes).' },
          { symbol: 'dRib', name: 'Deoxyribose — C₅H₁₀O₄', color: '#fb7185', desc: 'Found in DNA. Has a hydrogen (–H) instead of –OH at the 2\' carbon. More chemically stable — makes DNA the preferred long-term genetic archive.' },
          { symbol: 'ATP', name: 'ATP — Adenosine Triphosphate', color: '#fda4af', desc: 'A nucleotide derivative: ribose + adenine + 3 phosphate groups. The universal energy currency linking carbohydrate catabolism to cellular work.' },
        ],
      },
      {
        id: '03',
        title: 'Connection to Carbohydrates',
        type: 'text',
        content: `Every nucleotide in your genome contains a carbohydrate sugar. The 3 billion base pairs in human DNA each sit on a deoxyribose unit — meaning carbohydrates are quite literally the foundation of all hereditary information. Glucose metabolism (via the pentose phosphate pathway) is the primary biosynthetic route to ribose-5-phosphate, directly linking carbohydrate catabolism to DNA/RNA synthesis.`,
        credit: 'Kirellos George',
      },
    ],
  },

  {
    id: 'metabolism',
    label: 'Carb Metabolism',
    sublabel: 'Energy Pathways — Glycolysis',
    color: '#f97316',
    emissive: '#7c2d12',
    position: [0.5, 0.2, 3.2],
    size: 0.22,
    coords: { x: 128, y: 250, z: 6 },
    isPrimary: false,
    logs: [
      {
        id: '01',
        title: 'General Context',
        type: 'text',
        content: `Carbohydrate catabolism is the central highway of cellular energy production. Starting with glucose (C₆H₁₂O₆), cells extract energy through a series of enzyme-catalyzed reactions. The three main stages are Glycolysis (cytoplasm), the Krebs Cycle / Citric Acid Cycle (mitochondrial matrix), and Oxidative Phosphorylation (inner mitochondrial membrane).`,
        credit: 'Kirellos George',
      },
      {
        id: '02',
        title: 'Energy Pathway Stages',
        type: 'atoms',
        content: null,
        credit: 'Kirellos George',
        atoms: [
          { symbol: 'GL', name: 'Glycolysis', color: '#f97316', desc: 'Occurs in the cytoplasm. 1 glucose → 2 pyruvate + 2 ATP (net) + 2 NADH. Does not require oxygen (anaerobic). The universal energy pathway found in all living organisms.' },
          { symbol: 'KC', name: 'Krebs Cycle', color: '#fb923c', desc: 'Occurs in the mitochondrial matrix. 2 pyruvate → 6 CO₂ + 2 ATP + 8 NADH + 2 FADH₂. Requires oxygen. Completes the oxidation of glucose-derived carbon.' },
          { symbol: 'OP', name: 'Oxidative Phosphorylation', color: '#fbbf24', desc: 'Inner mitochondrial membrane. NADH & FADH₂ drive the electron transport chain → ~32-34 ATP via ATP synthase. The bulk ATP-producing stage (chemiosmosis).' },
          { symbol: 'PP', name: 'Pentose Phosphate Pathway', color: '#a3e635', desc: 'Alternative glucose pathway. Produces ribose-5-phosphate (for nucleotide synthesis) and NADPH (for reductive biosynthesis and antioxidant defense).' },
        ],
      },
      {
        id: '03',
        title: 'Total ATP Yield',
        type: 'text',
        content: `Complete aerobic oxidation of 1 glucose molecule: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + 36–38 ATP. This is roughly 40% efficiency — the remaining energy is released as heat (thermoregulation). Anaerobic fermentation yields only 2 ATP per glucose, explaining why aerobic organisms are energetically superior.`,
        credit: 'Kirellos George',
        highlight: true,
      },
    ],
  },
]

// ─── Team Members ─────────────────────────────────────────────────────────────
export const TEAM = [
  { id: 1, name: 'Kirellos George',   role: 'Lead Researcher , Website maker , UI/UX Designer , 3D Visualization',        field: 'Student', initial: 'KG', color: '#3ddc84' },
  { id: 2, name: 'David Bassem',     role: 'informtation getter',           field: 'student',         initial: 'DB', color: '#facc15' },
  { id: 3, name: 'Steven Ayman',     role: 'Information Getter',       field: 'Student',   initial: 'SA', color: '#f472b6' },
  { id: 4, name: 'Seif Mohmmed',     role: 'Information Getter',         field: 'Student',     initial: 'TM', color: '#f97316' },
  { id: 5, name: 'Flavio Hesham',     role: 'Information Getter',         field: 'Student',      initial: 'TM', color: '#22d3ee' },
]

// ─── Real Life Carbohydrate Sources ──────────────────────────────────────────
export const REAL_LIFE = [
  {
    id: 'rice',
    name: 'Rice',
    emoji: '🍚',
    carbType: 'Polysaccharide (Starch)',
    color: '#facc15',
    description: 'Rice is one of the world\'s most consumed staple foods. It is composed primarily of starch (70–80% of dry weight), which is a mixture of amylose (~20%) and amylopectin (~80%). During digestion, salivary and pancreatic amylase break the α-1,4 glycosidic bonds, releasing glucose for energy.',
    facts: ['~80% of dry weight is starch', 'White rice is lower in fiber than brown rice', 'Glycemic Index: 72 (high) for white rice', 'Provides ~130 kcal per 100g cooked'],
    carbs_per_100g: '28g',
  },
  {
    id: 'bread',
    name: 'Whole Wheat Bread',
    emoji: '🍞',
    carbType: 'Polysaccharide (Starch + Fiber)',
    color: '#fb923c',
    description: 'Bread is made from wheat flour — primarily starch and gluten. Whole wheat bread retains the bran, which contains cellulose (dietary fiber) — a structural β-glucan that humans cannot digest but which feeds gut microbiota (prebiotic function). White bread has most of its fiber removed.',
    facts: ['~45–50g carbs per 100g', 'Contains both starch and dietary fiber', 'Whole wheat has 6–7g fiber per 100g', 'Leavening (yeast) ferments sugars → CO₂'],
    carbs_per_100g: '49g',
  },
  {
    id: 'fruits',
    name: 'Fruits (Banana, Apple)',
    emoji: '🍎',
    carbType: 'Monosaccharides + Disaccharides',
    color: '#4ade80',
    description: 'Fruits are rich sources of monosaccharides (fructose, glucose) and the disaccharide sucrose. A ripe banana contains ~23g carbohydrates per 100g, primarily as glucose, fructose, and sucrose (with resistant starch in unripe bananas). Fructose is metabolized primarily in the liver without raising blood sugar as sharply as glucose.',
    facts: ['Fructose is sweeter than glucose', 'Unripe bananas: mostly resistant starch', 'Ripe bananas: mostly free sugars', 'Apples contain ~14g carbs, mostly fructose'],
    carbs_per_100g: '23g (banana)',
  },
  {
    id: 'potatoes',
    name: 'Potatoes',
    emoji: '🥔',
    carbType: 'Polysaccharide (Starch)',
    color: '#a78bfa',
    description: 'Potatoes are one of the most significant sources of dietary starch globally. They contain ~17g carbohydrates per 100g (raw), mostly as starch. When cooled after cooking, some starch retrograds into resistant starch (Type 3), which acts more like dietary fiber and has a lower glycemic index — a key concept in food science.',
    facts: ['~17g carbs per 100g (raw)', 'Resistant starch forms on cooling', 'High Glycemic Index when hot (baked: ~85)', 'Rich in potassium alongside carbs'],
    carbs_per_100g: '17g',
  },
  {
    id: 'honey',
    name: 'Honey',
    emoji: '🍯',
    carbType: 'Monosaccharides (Glucose + Fructose)',
    color: '#fbbf24',
    description: 'Honey is composed of approximately 38% fructose, 31% glucose, 9% other sugars, and ~17% water. Because it is already pre-digested by bee enzymes (invertase), the sugars are in monosaccharide form — rapidly absorbed. The high sugar content creates a low water activity that prevents microbial growth (natural preservative).',
    facts: ['~82g carbs per 100g', 'Pre-hydrolyzed by bee invertase enzyme', 'Antimicrobial due to low water activity + H₂O₂', 'Fructose:Glucose ratio ~1.2:1'],
    carbs_per_100g: '82g',
  },
  {
    id: 'legumes',
    name: 'Legumes (Lentils, Beans)',
    emoji: '🫘',
    carbType: 'Starch + Dietary Fiber',
    color: '#22d3ee',
    description: 'Legumes are outstanding sources of complex carbohydrates combined with protein. They contain resistant starch and various dietary fibers (pectin, cellulose) that are not digested in the small intestine but are fermented by gut bacteria in the colon, producing short-chain fatty acids (SCFAs) that benefit colon health and reduce inflammation.',
    facts: ['~20g carbs per 100g (cooked)', 'High in resistant starch + fiber', 'Low Glycemic Index (~30–40)', 'Fiber fermented → SCFAs (butyrate, propionate)'],
    carbs_per_100g: '20g',
  },
  {
    id: 'corn',
    name: 'Corn (Maize)',
    emoji: '🌽',
    carbType: 'Starch + Simple Sugars',
    color: '#f97316',
    description: 'Corn contains both starch (the primary energy store in the kernel endosperm) and smaller amounts of simple sugars (sweet corn varieties). It is the world\'s most produced cereal crop. High-fructose corn syrup (HFCS), derived from corn starch via enzymatic processing, is a major sweetener in processed foods.',
    facts: ['~19g carbs per 100g (sweet corn)', 'Source of high-fructose corn syrup (HFCS)', 'Popcorn: whole grain + dietary fiber', 'Maize starch: used in industry and food'],
    carbs_per_100g: '19g',
  },
  {
    id: 'milk',
    name: 'Milk',
    emoji: '🥛',
    carbType: 'Disaccharide (Lactose)',
    color: '#f472b6',
    description: 'Milk\'s primary carbohydrate is lactose — a disaccharide of glucose and galactose linked by a β-1,4 glycosidic bond. Digestion requires the enzyme lactase (β-galactosidase). After infancy, ~65% of the global population reduces lactase production (lactase non-persistence), causing lactose intolerance. Fermented dairy (yogurt, cheese) contains less lactose as bacteria have already broken it down.',
    facts: ['~5g lactose per 100ml', 'Requires lactase enzyme to digest', '65% of adults globally are lactose intolerant', 'Yogurt bacteria pre-digest lactose'],
    carbs_per_100g: '5g',
  },
]

// ─── Project Metadata ─────────────────────────────────────────────────────────
export const MAP_TEAM = {
  name: 'Kirellos George',
  role: 'Lead Researcher , Website maker , UI/UX Designer , 3D Visualization',
  timestamp: '2026-05-05',
  version: 'v2.1.0',
}
